# fly.toml app configuration file generated for aus-grocery-price-database on 2024-07-21T11:16:13+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aus-grocery-price-database'
primary_region = 'syd'

[build]
  [build.args]
    GO_VERSION = '1.22.5'

[env]
  PORT = '8080'
  LOCAL_WOOLWORTHS_DB_PATH = '/data/woolworths.db3'
  MAX_PRODUCT_AGE_MINUTES = 120
  WOOLWORTHS_URL = 'https://www.woolworths.com.au'
  INFLUXDB_UPDATE_RATE_SECONDS = 2
  DEBUG_LOGGING = 'true'


[[vm]]
  memory_mb = 256
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "local_database"
  destination = "/data"

