# fly.toml app configuration file generated for aus-grocery-price-database-grafana on 2024-07-23T21:21:42+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aus-grocery-price-database-grafana'
primary_region = 'syd'

[build]
#   image = 'grafana/grafana:10.0.0'
  [build.args]
    BASE_IMAGE = 'grafana/grafana:10.0.0'

[env]
# TODO make sure there isn't anything important written to any of these directories.
#   GF_PATHS_HOME = '/data/usr/share/grafana'
#   GF_PATHS_LOGS = '/data/var/log/grafana'
#   GF_PATHS_PLUGINS = '/data/var/lib/grafana/plugins'
#   GF_PATHS_PROVISIONING = '/data/etc/grafana/provisioning'
  GF_PATHS_CONFIG = '/etc/grafana/grafana.ini'
  GF_PATHS_DATA = '/data/var/lib/grafana'
  GF_DEFAULT_INSTANCE_NAME = 'aus-grocery-price-database-grafana'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'grafana_database'
  destination = '/data'
