{
 "title": "Groceries",
 "time": { "from": "2024-07-24T11:58:47.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "UserSelectedProduct",
    "label": "Select products to plot",
    "query": "show tag values from \"product\" WITH key = \"name\" WHERE time >= now() - 1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Price over time of selected products",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "price::field" ], "type": "tag" }
     ],
     "measurement": "product",
     "query": "SELECT mean(\"cents\")  / 100 FROM \"autogen\".\"product\" WHERE (\"name\"::tag =~ /.*$UserSelectedProduct.*/) AND $timeFilter GROUP BY *, time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "cents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=~", "value": "/^$UserSelectedProduct$/" }
     ]
    }
   ]
  },
  {
   "title": "Recent price changes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "measurement": "product",
     "query": "SELECT \"store\",\"name\",\"cents_change\"/100,\"cents\"/100 FROM \"autogen\".\"product\" WHERE (\"cents_change\"::field != 0) AND time >= now()-5d ORDER BY time DESC LIMIT 10",
     "select": [
      [
       { "params": [ "cents_change" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cents_change::field", "operator": "!=", "value": "''" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 17 },
   "options": {
    "content": "# AUSCost\n\nHi! Welcome to [AUSCost](https://auscost.com.au)! Thanks for visiting.\n\nThis is an open database of grocery prices in Australia. Its goal is to track long-term price trends to help make good purchasing decisions and hold grocery stores to account for price increases. You're currently looking at the raw data. I know it's not very beautiful yet! It's early days.\n\nThis project is [open source](https://github.com/tjhowse/aus_grocery_price_database), which means anyone is welcome to contribute. I'm looking for collaborators to help with improving the frontend (the thing you're looking at). [Hit me up](mailto:hi@auscost.com.au) if you're interested in lending a hand.\n\nHosting this service is fairly cheap, but not free, and I'm working on it in my spare time. If you feel this project is worthwhile, and you are able, please consider helping with running costs and development via [PayPal](https://www.paypal.com/paypalme/tjhowse), PayID (hi@auscost.com.au) or a [Github Sponsorship](https://github.com/sponsors/tjhowse).\n\nIf you have any feedback please [email](mailto:hi@auscost.com.au) me or create a Github issue. I'm very keen to learn about ideas for different use-cases! I'm also amenable to providing API keys for (respectful) direct access to the price history database for other cool spinoff projects."
   }
  },
  {
   "title": "Total tracked product count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total_product_count\") FROM \"autogen\".\"system\""
    }
   ]
  },
  {
   "title": "Fruit & Veg",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "Royal Gala Apple",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "product",
     "select": [
      [
       { "params": [ "cents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department::tag", "operator": "=", "value": "Fruit & Veg" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/.*Apple Royal Gala.*/" }
     ]
    },
    {
     "alias": "Cavendish Banana",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "product",
     "select": [
      [
       { "params": [ "cents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department::tag", "operator": "=", "value": "Fruit & Veg" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/.*Cavendish Banana.*/" }
     ]
    },
    {
     "alias": "Navel Orange",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "product",
     "select": [
      [
       { "params": [ "cents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department::tag", "operator": "=", "value": "Fruit & Veg" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/.*Orange Navel Each.*/" }
     ]
    },
    {
     "alias": "Mandarin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "product",
     "query": "SELECT mean(\"cents\")  / 100 FROM \"autogen\".\"product\" WHERE (\"department\"::tag = 'Fruit & Veg' AND \"name\"::tag = ' Mandarin Afourer  Each') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "cents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department::tag", "operator": "=", "value": "Fruit & Veg" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/.*Mandarin Afourer Each.*/" }
     ]
    },
    {
     "alias": "Tomato",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "product",
     "query": "SELECT mean(\"cents\")  / 100 FROM \"autogen\".\"product\" WHERE (\"department\"::tag = 'Fruit & Veg' AND \"name\"::tag = ' Fresh Tomato  Each') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "cents" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "department::tag", "operator": "=", "value": "Fruit & Veg" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/.*Fresh Tomato Each.*/" }
     ]
    }
   ]
  }
 ]
}