{
 "title": "System Info",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "AGPD Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"version\") FROM \"autogen\".\"system\" WHERE (\"service\"::tag = 'agpd')",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=", "value": "agpd" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "RAM Utilisation (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "ram_utilisation_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Product updates per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Products Per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "products_per_second" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AGPD Hard drive utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "HDD Bytes Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "hdd_bytes_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total product count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Total product count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "total_product_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "InfluxDB Groceries Bucket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "storage_shard_disk_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bucket::tag", "operator": "=", "value": "01c1ca212aa54ac6" }
     ]
    },
    {
     "alias": "InfluxDB System Bucket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "storage_shard_disk_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bucket::tag", "operator": "=", "value": "23dc0539ec71d649" }
     ]
    }
   ]
  }
 ]
}